# Generated by Django 5.0.2 on 2025-06-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[('pre-med', 'Pre-Med'), ('other', 'Other'), ('pre-dental', 'Pre-Dental'), ('business', 'Business'), ('tech', 'Technology'), ('arts', 'Arts')], default='other', max_length=20),
        ),
    ]
