# Generated by Django 5.0.2 on 2025-06-17 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_club_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[('other', 'Other'), ('arts', 'Arts'), ('business', 'Business'), ('pre-med', 'Pre-Med'), ('tech', 'Technology'), ('pre-dental', 'Pre-Dental')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='ClubInterested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('interested', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_clubs', to='clubs.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_clubs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('club', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='ClubSeen',
        ),
    ]
