# Generated by Django 5.0.2 on 2025-06-24 22:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_club_category_clubinterested_delete_clubseen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClubInterested',
            new_name='ClubUserConnector',
        ),
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[('business', 'Business'), ('pre-med', 'Pre-Med'), ('tech', 'Technology'), ('pre-dental', 'Pre-Dental'), ('other', 'Other'), ('arts', 'Arts')], default='other', max_length=20),
        ),
    ]
