# Generated by Django 4.2.10 on 2025-06-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_club_category_clubinterested_delete_clubseen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[('pre-med', 'Pre-Med'), ('other', 'Other'), ('business', 'Business'), ('arts', 'Arts'), ('tech', 'Technology'), ('pre-dental', 'Pre-Dental')], default='other', max_length=20),
        ),
    ]
