# Generated by Django 5.0.2 on 2025-06-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_rename_clubinterested_clubuserconnector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubuserconnector',
            name='started_prep',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[('business', 'Business'), ('arts', 'Arts'), ('other', 'Other'), ('pre-dental', 'Pre-Dental'), ('pre-med', 'Pre-Med'), ('tech', 'Technology')], default='other', max_length=20),
        ),
    ]
