# Generated by Django 4.2.10 on 2025-06-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_club_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[('arts', 'Arts'), ('pre-med', 'Pre-Med'), ('pre-dental', 'Pre-Dental'), ('business', 'Business'), ('other', 'Other'), ('tech', 'Technology')], default='other', max_length=20),
        ),
    ]
