# Generated by Django 5.0.2 on 2025-06-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_clubuserconnector_started_prep_alter_club_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('business', 'Business'), ('pre-med', 'Pre-Med'), ('pre-dental', 'Pre-Dental'), ('arts', 'Arts'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
