# Generated by Django 5.0.2 on 2025-08-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_alter_club_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[('top 50', 'Top 50 (Recommended)'), ('consulting', 'Consulting'), ('finance', 'Finance'), ('business fraternity', 'Business Fraternity'), ('tech', 'Technology'), ('business', 'Business'), ('pre-med', 'Pre-Med'), ('pre-dental', 'Pre-Dental'), ('arts', 'Arts'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
