# Generated by Django 4.2.10 on 2025-06-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_alter_club_category'),
        ('clubs', '0006_alter_club_category'),
    ]

    operations = [
    ]
