# Generated by Django 4.2.10 on 2025-06-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_merge_20250626_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('business', 'Business'), ('pre-med', 'Pre-Med'), ('pre-dental', 'Pre-Dental'), ('arts', 'Arts'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
