# Generated by Django 5.0.2 on 2025-08-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_alter_club_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[('top 50', 'Top 50 (Recommended)'), ('consulting', 'Consulting'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('business fraternity', 'Business Fraternity'), ('tech', 'Technology'), ('pre-med', 'Pre-Med'), ('pre-dental', 'Pre-Dental'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
