# Generated by Django 5.0.2 on 2025-08-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_alter_club_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
