# Generated by Django 5.0.2 on 2025-06-25 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0006_alter_club_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('question_text', models.TextField()),
                ('category', models.CharField(choices=[('tech', 'Technology'), ('business', 'Business'), ('pre-med', 'Pre-Med'), ('pre-dental', 'Pre-Dental'), ('arts', 'Arts'), ('other', 'Other')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('question_type', models.CharField(choices=[('behavioral', 'Behavioral'), ('technical', 'Technical'), ('case_study', 'Case Study'), ('brain_teaser', 'Brain Teaser'), ('general', 'General')], default='general', max_length=20)),
                ('sample_answer', models.TextField(blank=True, null=True)),
                ('hints', models.TextField(blank=True, null=True)),
                ('time_limit_minutes', models.IntegerField(default=5, help_text='Suggested time limit in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'difficulty', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('tech', 'Technology'), ('business', 'Business'), ('pre-med', 'Pre-Med'), ('pre-dental', 'Pre-Dental'), ('arts', 'Arts'), ('other', 'Other')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('question_count', models.IntegerField(default=5)),
                ('time_limit_minutes', models.IntegerField(default=30)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('total_score', models.IntegerField(blank=True, null=True)),
                ('questions_attempted', models.IntegerField(default=0)),
                ('questions_correct', models.IntegerField(default=0)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='clubs.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInterviewProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, help_text='Score out of 100', null=True)),
                ('time_taken_minutes', models.FloatField(blank=True, null=True)),
                ('user_answer', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text="User's notes about their performance", null=True)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_practice', to='clubs.club')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attempts', to='interviews.interviewquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-attempted_at'],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
