# Generated by Django 5.0.2 on 2025-06-25 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_alter_club_category'),
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewquestion',
            options={'ordering': ['difficulty', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='interviewquestion',
            name='category',
        ),
        migrations.CreateModel(
            name='ClubQuestionConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_connections', to='clubs.club')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_connections', to='interviews.interviewquestion')),
            ],
            options={
                'unique_together': {('club', 'question')},
            },
        ),
    ]
