# Generated by Django 5.0.2 on 2025-06-25 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_alter_interviewquestion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinterviewprogress',
            name='club',
        ),
    ]
