# Generated by Django 5.0.2 on 2025-06-26 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_alter_club_category'),
        ('interviews', '0003_remove_userinterviewprogress_club'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinterviewprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userinterviewprogress',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_progress', to='clubs.club'),
        ),
        migrations.AlterUniqueTogether(
            name='userinterviewprogress',
            unique_together={('user', 'question', 'club')},
        ),
    ]
