# Generated by Django 5.0.2 on 2025-06-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_userinterviewprogress_audio_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterviewprogress',
            name='audio_uploaded_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
