# Generated by Django 5.0.2 on 2025-06-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_alter_userinterviewprogress_audio_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinterviewprogress',
            name='audio_uploaded_at',
        ),
        migrations.RemoveField(
            model_name='userinterviewprogress',
            name='response_audio',
        ),
    ]
