# Generated by Django 5.0.2 on 2025-07-12 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0007_remove_userinterviewprogress_audio_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='current_question_index',
            field=models.IntegerField(default=0, help_text='Index of current question (0-based)'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='question_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_question_1', to='interviews.interviewquestion'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='question_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_question_2', to='interviews.interviewquestion'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='question_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_question_3', to='interviews.interviewquestion'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='question_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_question_4', to='interviews.interviewquestion'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='question_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_question_5', to='interviews.interviewquestion'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='time_remaining_seconds',
            field=models.IntegerField(blank=True, help_text='Time remaining in seconds', null=True),
        ),
    ]
