# Generated by Django 5.0.2 on 2025-07-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0008_interviewsession_current_question_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewsession',
            name='question_1',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='question_2',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='question_3',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='question_4',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='question_5',
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='questions',
            field=models.JSONField(default=list, help_text='List of question IDs for this session'),
        ),
    ]
