# Generated by Django 5.0.2 on 2025-07-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0009_remove_interviewsession_question_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewsession',
            name='questions_correct',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='time_remaining_seconds',
        ),
    ]
