# Generated by Django 5.0.2 on 2025-07-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0010_remove_interviewsession_questions_correct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewsession',
            name='questions_attempted',
        ),
    ]
