# Generated by Django 5.0.2 on 2025-07-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0011_remove_interviewsession_questions_attempted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterviewprogress',
            name='feedback',
            field=models.TextField(blank=True, help_text='Feedback from AI', null=True),
        ),
        migrations.AlterField(
            model_name='userinterviewprogress',
            name='score',
            field=models.IntegerField(blank=True, help_text='Score out of 5', null=True),
        ),
    ]
