# Generated by Django 5.0.2 on 2025-08-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0012_userinterviewprogress_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='case_context',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userinterviewprogress',
            name='score',
            field=models.FloatField(blank=True, help_text='Score out of 5', null=True),
        ),
    ]
