# Generated by Django 5.0.2 on 2025-08-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0014_alter_interviewsession_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='category',
            field=models.CharField(choices=[('top 50', 'Top 50 (Recommended)'), ('consulting', 'Consulting'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('business fraternity', 'Business Fraternity'), ('tech', 'Technology'), ('pre-med', 'Pre-Med'), ('pre-dental', 'Pre-Dental'), ('other', 'Other')], max_length=20),
        ),
    ]
