# Generated by Django 5.0.2 on 2025-08-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0015_alter_interviewsession_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterviewprogress',
            name='notes',
            field=models.TextField(blank=True, default='', help_text="User's notes about their performance"),
        ),
        migrations.AlterField(
            model_name='userinterviewprogress',
            name='user_answer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
